// src/types/folder.ts

/**
 * Represents a folder in the link library.
 *
 * Folders form a tree using parentId:
 *
 * Root
 * ├── Programming
 * │   ├── React
 * │   └── TypeScript
 * └── AI
 */
export interface Folder {
  /** Unique folder ID (generated by Dexie) */
  id?: number;

  /** Folder name */
  name: string;

  /**
   * Parent folder ID.
   * null indicates this is a root-level folder.
   */
  parentId: number | null;

  /** Date the folder was created */
  createdAt: Date;

  /** Date the folder was last modified */
  updatedAt: Date;
}

/**
 * Used when creating a new folder.
 * The database will generate the ID.
 */
export type CreateFolderInput = Omit<Folder, "id">;

/**
 * Used when editing a folder.
 * Only supplied fields will be updated.
 */
export type UpdateFolderInput = Partial<CreateFolderInput>;

/**
 * Folder with nested children.
 *
 * This is not stored in IndexedDB.
 * It is created in memory when rendering the folder tree.
 */
export interface FolderNode extends Folder {
  children: FolderNode[];
}