// src/types/link.ts

/**
 * Represents a saved link in the library.
 */
export interface Link {
  /** Unique ID generated by Dexie */
  id?: number;

  /** Page title */
  title: string;

  /** Website URL */
  url: string;

  /** Optional description of the page */
  description?: string;

  /** Website favicon URL */
  favicon?: string;

  /** Folder containing this link */
  folderId: number;

  /** Optional tags */
  tags: string[];

  /** Favorite status */
  favorite: boolean;

  /** Date the link was created */
  createdAt: Date;

  /** Date the link was last updated */
  updatedAt: Date;
}

/**
 * Input type when creating a new link.
 * The database generates the ID.
 */
export type CreateLinkInput = Omit<Link, "id">;

/**
 * Input type when updating an existing link.
 * Allows partial updates.
 */
export type UpdateLinkInput = Partial<CreateLinkInput>;